#pragma config(Sensor, S4,     SonarSensor,    sensorSONAR)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          LeftMotor,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          RightMotor,    tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int msecBack = 625;

int turns_mas[4] = {1, -1, 1, 1};
int turnNumber = 0;

void turnRight()
{
	motor[motorB] = 60;
	motor[motorC] = -60;
}

void turnLeft()
{
	motor[motorB] = -60;
	motor[motorC] = 60;
}

void turn(int tnum)
{
	const float k = 200.0 / 90.0;
	volatile float t = 90.0 * k;

	nMotorEncoder[motorB] = 0;
	nMotorEncoder[motorC] = 0;

	while(abs(nMotorEncoder[motorB]) <= t || abs(nMotorEncoder[motorC]) <= t)
	{
		if (tnum == 1)
		{
			turnLeft();
		}
		else if (tnum == -1)
		{
			turnRight();
		}
	}
}

task main()
{
	while (true)
	{
		while (SensorValue[S4] > 10)
		{
			motor[motorB] = 60;
			motor[motorC] = 60;
		}

		motor[motorB] = 0;
		motor[motorC] = 0;

		motor[motorB] = -60;
		motor[motorC] = -60;

		if (turns_mas[turnNumber] == -1)
		{
			wait1Msec(msecBack + 42);
		}
		else
		{
			wait1Msec(msecBack);
		}

		turn(turns_mas[turnNumber]);

		turnNumber += 1;
	}
}
